### ISSUE TITLE
Phong Shading

### ISSUE THREAD

**Issue by jojojojojojo** [rohan-collins/MATLAB-GLTF#4]
Dear Rohan,
awesome toolbox, really, really helpful!! The final bit missing for me (note, that I am an absolute noob concerning rendering...) is, that the guy who works with my exported gltf file requires phong shading capabilities.. and I was wondering, if you can tell me how this could be considered in the toolbox. Maybe its already in there, but I am just not experienced enough to find it..
As I understand it has to to with edge smoothing.. Maybe adding vertex normals to the gltf data helps with that? in "addMesh" you have an option ('normals',TRUE). Or maybe has to to with "addMaterial"?
It would be awesome if you could give me a hint if phong shading is something doable within the toolbox..
Thanks so much!
Best regards,
Johannes

**Comment by rohan-collins** [comment]
Hi Johannes,

As mentioned in the [glTF 2.0 Specifications](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#materials-overview), "glTF defines materials using a common set of parameters that are based on widely used material representations from Physically Based Rendering (PBR)". PBR is a shading model as is Phong, but they are completely different and non-interchangeable. Phong is very primitive, which is why I presume Khronos went for PBR over Phong for glTF.

That being said, glTF 1.0, which is a deprecated standard, had an extension called [KHR_materials_common](https://github.com/KhronosGroup/glTF/tree/main/extensions/1.0/Khronos/KHR_materials_common), which also has been deprecated along with glTF 1.0. This might have some of the features you are looking for, but I do not recommend going that way. If you feel that your use case requires this lighting model, you can [request](https://github.com/KhronosGroup/glTF/issues) it, but that will be up to Khronos. I don't believe there are any current vendor extensions that do what you need.

As far as the toolbox is concerned, it is meant to output glTF 2.0 compatible files. I have tried to implement as many glTF 2.0 extensions as possible, and I would ask contributors to add the handling for any more that they need, but I cannot support adding a deprecated standard for a previous version of the standard. You can edit the GLTF object after creation like you would a struct, so you might be able to write a small script to add data for the above extensions that your guy can use. A warning though: while technically renderers are supposed to disregard any extension they cannot handle, I am not sure whether the final output can be considered a valid glTF 2.0 file.

I am sorry I cannot add support for a non-ratified extension, but hope the links above help.

Rohan

**Comment by jojojojojojo** [comment]
Hi Rohan,
thanks a lot for your quick reply, totally get your point. I will talk to
the render people and see if they can somehow work with the newer PBR
GLTF2.0 standard. For this one your toolbox already allows for specifying
parameters like specularFactor glossinessFactor, I saw.. I will see if they
can somehow solve the issue they have with visible edges in the rendering
(which apparently with phong shading are not there anymore..).
If you have a hint on how this edge-problem might be handled by PBR, please
let me know:-))
Thanks again!
Best regards,
Johannes


Am Fr., 17. März 2023 um 15:46 Uhr schrieb Rohan Chabukswar <
***@***.***>:

**Comment by rohan-collins** [comment]
Hi Johannes,

Maybe ask on the Khronos glTF Github? Most people there are very responsive.

Rohan

**Comment by rohan-collins** [comment]
Sure, my email address is  rohan.chabukswar@collins.com. But I am not sure I’ll be able to help!
